version: "3.8"
services:
  mongo:
    image: "mongo"
    expose:
      - 27017
    command: --quiet
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
  rabbitmq:
    image: "rabbitmq:management"
    expose:
      - 5672
      - 5673
    ports:
      - "15672:15672"
    logging:
      driver: none
  trompa:
    build: .
    ports:
      - ${TROMPA_API_PORT}:${TROMPA_API_PORT}
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./scriptoria/src/assets/omr_files:/omr_files
      - ./logs:/logs
    command:  sh -c "./wait && ./bash_scripts/docker_start.sh"
    tty: true
    privileged: true
    environment:
      WAIT_HOSTS: mongo:27017, rabbitmq:5672
      MODE: ${TROMPA_BACKEND_MODE}
      API_PORT: ${TROMPA_API_PORT}