# Addresses ("ip:port")
mongodb_address|ip: "mongo:27017"
rabbitmq_address|ip: "rabbitmq:5672"
measure_detector_address|ip: "measure-detector:8000"

# Mongo DB
db_name: "trompa_test"
col_slice: "slices"
col_score: "scores"
col_sheet: "sheets"
col_aggregated_result: "results_agg"
col_result: "results"
col_task: "tasks"
col_task_context: "task_context"
col_submitted_task: "submitted_tasks"
col_task_type: "task_types"
col_task_batch: "task_batches"
col_campaign_status: "campaign_status"

# Rabbit MQ
mq_new_item: "measure_detector_queue"
mq_sheet: "sheet_queue"
mq_score: "score_queue"
mq_slicer: "slicer_queue"
mq_score_rebuilder: "score_rebuilder_queue"
mq_aggregator: "aggregator_queue"
mq_github_init: "github_init_queue"
mq_github: "github_queue"
mq_aggregator_xml: "aggregator_xml_queue"
mq_aggregator_form: "aggregator_form_queue"
mq_omr_planner: "omr_planner_queue"
mq_omr_planner_status: "omr_planner_status_queue"
mq_task_scheduler: "task_scheduler_queue"
mq_task_scheduler_status: "task_scheduler_status_queue"
mq_ce_communicator: "ce_communicator_queue"
mq_aligner: "aligner_queue"
mq_form_processor: "form_processor_queue"
mq_task_passthrough: "task_passthrough_queue"

# Paths
upload_folder|path: "/omr_files/"
base_sheet_path|path: "/omr_files/"

# Github
github_user: ""
github_token: ""
github_organization: ""
github_branch: ""
delete_if_exists|bool: true  # Delete github repo if it already exists. Mostly for testing, should be off in production to prevent accidental deletions
only_commit_if_changed|bool: true  # Only commit when there was a change
github_enable|bool: true

# Aggregator
aggregator_xml_threshold|float|0...1: 0.6
aggregator_form_threshold|float|0...1: 0.6

# Other
skip_measure_detection|bool: false # Assumes there's a pre-made skeleton present already for the score if true
use_cert|bool: false
ce_server: "https://api-test.trompamusic.eu/" # Should be dummy server
current_server: ""
entrypoint_id: ""
processing_potentialaction_id: ""
verify_potentialaction_id: ""